import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./_components/SessionProvider";
import NavMenu from "./_components/NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = getServerSession();

  return (
    <html lang="en">
      <body
        className={`bg-gray-100 min-h-screen flex items-center justify-center ${inter.className}`}
      >
        <SessionProvider session={session}>
          <main className="max-w-screen-xl mx-auto p-4">
            <NavMenu />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
